// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlarijlhllzjqvxdigds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYXJpamxobGx6anF2eGRpZ2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjM0MDksImV4cCI6MjA2MzY5OTQwOX0.DgGfzD0YfQ3HlqxnkHjLPtAy6Nbx65J6TzbX2LVIVNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});